export const SignInActionTypes = {
    OPEN_SIGN_IN: 'OPEN_SIGN_IN',
    CLOSE_SIGN_IN: 'CLOSE_SIGN_IN',
    CHANGE_FORM: 'CHANGE_FORM',
    PASSWORD_ERROR: 'PASSWORD_ERROR',
    TOGGLE_IS_REGISTERED: 'TOGGLE_IS_REGISTERED'
};

export default SignInActionTypes;