export const RecipeActionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    DELETE_INGREDIENT: 'DELETE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS',
    ADD_STEP: 'ADD_STEP',
    DELETE_STEP: 'DELETE_STEP'
}

export default RecipeActionTypes;